package ru.titov.taskmanagerserver.endpoint.task;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-16T15:07:23.550+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://task.endpoint.taskmanagerserver.titov.ru/", name = "TaskEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface TaskEndpoint {

    @WebMethod
    @Action(input = "http://task.endpoint.taskmanagerserver.titov.ru/TaskEndpoint/removeRequest", output = "http://task.endpoint.taskmanagerserver.titov.ru/TaskEndpoint/removeResponse")
    @RequestWrapper(localName = "remove", targetNamespace = "http://task.endpoint.taskmanagerserver.titov.ru/", className = "ru.titov.taskmanagerserver.endpoint.task.Remove")
    @ResponseWrapper(localName = "removeResponse", targetNamespace = "http://task.endpoint.taskmanagerserver.titov.ru/", className = "ru.titov.taskmanagerserver.endpoint.task.RemoveResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.titov.taskmanagerserver.endpoint.task.Response remove(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "taskOrderIndex", targetNamespace = "")
        java.lang.Integer taskOrderIndex
    );

    @WebMethod
    @Action(input = "http://task.endpoint.taskmanagerserver.titov.ru/TaskEndpoint/viewAllRequest", output = "http://task.endpoint.taskmanagerserver.titov.ru/TaskEndpoint/viewAllResponse")
    @RequestWrapper(localName = "viewAll", targetNamespace = "http://task.endpoint.taskmanagerserver.titov.ru/", className = "ru.titov.taskmanagerserver.endpoint.task.ViewAll")
    @ResponseWrapper(localName = "viewAllResponse", targetNamespace = "http://task.endpoint.taskmanagerserver.titov.ru/", className = "ru.titov.taskmanagerserver.endpoint.task.ViewAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.titov.taskmanagerserver.endpoint.task.TaskListResponse viewAll(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    );

    @WebMethod
    @Action(input = "http://task.endpoint.taskmanagerserver.titov.ru/TaskEndpoint/updateRequest", output = "http://task.endpoint.taskmanagerserver.titov.ru/TaskEndpoint/updateResponse")
    @RequestWrapper(localName = "update", targetNamespace = "http://task.endpoint.taskmanagerserver.titov.ru/", className = "ru.titov.taskmanagerserver.endpoint.task.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://task.endpoint.taskmanagerserver.titov.ru/", className = "ru.titov.taskmanagerserver.endpoint.task.UpdateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.titov.taskmanagerserver.endpoint.task.Response update(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "taskOrderIndex", targetNamespace = "")
        java.lang.Integer taskOrderIndex,
        @WebParam(name = "projectOrderIndex", targetNamespace = "")
        java.lang.Integer projectOrderIndex,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description
    );

    @WebMethod
    @Action(input = "http://task.endpoint.taskmanagerserver.titov.ru/TaskEndpoint/createRequest", output = "http://task.endpoint.taskmanagerserver.titov.ru/TaskEndpoint/createResponse")
    @RequestWrapper(localName = "create", targetNamespace = "http://task.endpoint.taskmanagerserver.titov.ru/", className = "ru.titov.taskmanagerserver.endpoint.task.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://task.endpoint.taskmanagerserver.titov.ru/", className = "ru.titov.taskmanagerserver.endpoint.task.CreateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.titov.taskmanagerserver.endpoint.task.Response create(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "projectOrderIndex", targetNamespace = "")
        java.lang.Integer projectOrderIndex,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description
    );

    @WebMethod
    @Action(input = "http://task.endpoint.taskmanagerserver.titov.ru/TaskEndpoint/viewRequest", output = "http://task.endpoint.taskmanagerserver.titov.ru/TaskEndpoint/viewResponse")
    @RequestWrapper(localName = "view", targetNamespace = "http://task.endpoint.taskmanagerserver.titov.ru/", className = "ru.titov.taskmanagerserver.endpoint.task.View")
    @ResponseWrapper(localName = "viewResponse", targetNamespace = "http://task.endpoint.taskmanagerserver.titov.ru/", className = "ru.titov.taskmanagerserver.endpoint.task.ViewResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.titov.taskmanagerserver.endpoint.task.TaskResponse view(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "taskOrderIndex", targetNamespace = "")
        java.lang.Integer taskOrderIndex
    );
}
